name: Notify on Merge to Main

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:

jobs:
  notify:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Notify via Slack
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"PR #${{ github.event.pull_request.number }} was *merged* into `main` by ${{ github.actor }}"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify Stakeholders via Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.MAIL_HOST }}
          server_port: ${{ secrets.MAIL_PORT }}
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "PR #${{ github.event.pull_request.number }} merged to main"
          body: |
            The following pull request has been merged into the main branch:

            Title: ${{ github.event.pull_request.title }}
            Author: ${{ github.event.pull_request.user.login }}
            Merged by: ${{ github.actor }}
            URL: ${{ github.event.pull_request.html_url }}
          to: |
            mohd20sharik@gmail.com
          from: GitHub Actions <${{ secrets.MAIL_USERNAME }}>
